//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroTech1._2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblATNodesSensorsConnection
    {
        public long id { get; set; }
        public Nullable<long> node_id { get; set; }
        public Nullable<long> sensor_id { get; set; }
    
        public virtual tblATNode tblATNode { get; set; }
        public virtual tblATSensor tblATSensor { get; set; }
    }
}
