//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroTech1._2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblATNode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblATNode()
        {
            this.tblATNodesSensorsConnections = new HashSet<tblATNodesSensorsConnection>();
            this.tblATPlants = new HashSet<tblATPlant>();
        }
    
        public long node_id { get; set; }
        public string node_name { get; set; }
        public string node_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblATNodesSensorsConnection> tblATNodesSensorsConnections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblATPlant> tblATPlants { get; set; }
    }
}
