//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroTech1._2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viATAllNodesData
    {
        public string node { get; set; }
        public string sensor { get; set; }
        public Nullable<decimal> avg_value { get; set; }
        public string measuring_unit { get; set; }
        public string Start_time { get; set; }
        public string End_time { get; set; }
        public long id { get; set; }
    }
}
